# Generated by Django 4.2.4 on 2023-08-28 03:45

from django.db import migrations, models
import django.utils.timezone
import things.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, max_length=128, null=True, upload_to=things.models.app_directory_path)),
                ('content_type', models.CharField(blank=True, max_length=128, null=True)),
                ('size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderThing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing_type', models.CharField(max_length=150)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
