# Generated by Django 4.2.4 on 2023-08-10 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='user',
        ),
    ]
