name: frontend

on:
  push:
    branches:
      - '**'
    paths:
      - 'frontend/wc/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'frontend/wc/**'

jobs:
  tests:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
        cache: npm
        working-directory: frontend/wc

    - name: install packages
      run: npm install
      working-directory: frontend/wc
    - name: lint
      run: npm run lint
      working-directory: frontend/wc
    - name: build
      run: npm run build
      working-directory: frontend/wc
