name: frontend

on:
  push:
    branches:
      - '**'
    paths:
      - 'frontend/wc/**'
  pull_request:
    branches:
      - '**'
    paths:
      - 'frontend/wc/**'

jobs:
  tests:

    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: frontend/wc

    steps:
    - uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.x
        cache: yarn
        cache-dependency-path: frontend/wc/yarn.lock

    - name: install packages
      run: yarn install
    - name: lint
      run: yarn lint
    - name: build
      run: yarn build
